### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by KingOfTheNOPs** [KingOfTheNOPs/cookie-monster#13]
TODO: add support for decrypting Edge App Bound Key and Cookie DB

**Comment by Mikazukitanjiro** [comment]
Hello do you have telegram or signal app we can talk would love some insight on how to use this stealer

**Comment by KingOfTheNOPs** [comment]
I have neither

**Comment by Mikazukitanjiro** [comment]
Where can we char privately
