### ISSUE TITLE
could not read bof file

### ISSUE THREAD

**Issue by 1483769879** [KingOfTheNOPs/cookie-monster#14]
<img width="366" alt="image" src="https://github.com/user-attachments/assets/5820f681-60cc-41dd-93a5-5fd3382b60d6">

**Comment by KingOfTheNOPs** [comment]
In the recent updated, the aggressor script and makefile to look for cookie-monster-bof.[architecture].o (i.e. cookie-monster-bof.x64.o). Does the directory the BOF is compiled in have the updated object files?

**Comment by KingOfTheNOPs** [comment]
Did that work for you?

**Comment by KingOfTheNOPs** [comment]
closing, please reopen if issues persist, but no issues occurred when I was retesting
