### ISSUE TITLE
Error during Make

### ISSUE THREAD

**Issue by 7h3pr0xy** [KingOfTheNOPs/cookie-monster#4]
┌──(root㉿pr0xy)-[/home/pr0xy/Documents/tools/cookie-monster]
└─# make                                
x86_64-w64-mingw32-gcc -c cookie-monster-bof.c -o cookie-monster-bof.o
cookie-monster-bof.c: In function ‘GetFileContent’:
cookie-monster-bof.c:89:34: warning: passing argument 1 of ‘KERNEL32$CreateFileA’ from incompatible pointer type [-Wincompatible-pointer-types]
   89 |     hFile = KERNEL32$CreateFileA(appdata, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
      |                                  ^~~~~~~
      |                                  |
      |                                  CHAR * {aka char *}
cookie-monster-bof.c:24:57: note: expected ‘LPCWSTR’ {aka ‘const short unsigned int *’} but argument is of type ‘CHAR *’ {aka ‘char *’}
   24 | WINBASEAPI HANDLE  WINAPI KERNEL32$CreateFileA (LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
      |                                                 ~~~~~~~~^~~~~~~~~~
cookie-monster-bof.c: In function ‘GetFirefoxInfo’:
cookie-monster-bof.c:250:34: warning: passing argument 1 of ‘KERNEL32$CreateFileA’ from incompatible pointer type [-Wincompatible-pointer-types]
  250 |     hFile = KERNEL32$CreateFileA(appdata, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
      |                                  ^~~~~~~
      |                                  |
      |                                  CHAR * {aka char *}
cookie-monster-bof.c:24:57: note: expected ‘LPCWSTR’ {aka ‘const short unsigned int *’} but argument is of type ‘CHAR *’ {aka ‘char *’}
   24 | WINBASEAPI HANDLE  WINAPI KERNEL32$CreateFileA (LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
      |                                                 ~~~~~~~~^~~~~~~~~~
cookie-monster-bof.c:302:34: warning: passing argument 1 of ‘KERNEL32$CreateFileA’ from incompatible pointer type [-Wincompatible-pointer-types]
  302 |     hFile = KERNEL32$CreateFileA(logins, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
      |                                  ^~~~~~
      |                                  |
      |                                  CHAR * {aka char *}
cookie-monster-bof.c:24:57: note: expected ‘LPCWSTR’ {aka ‘const short unsigned int *’} but argument is of type ‘CHAR *’ {aka ‘char *’}
   24 | WINBASEAPI HANDLE  WINAPI KERNEL32$CreateFileA (LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
      |                                                 ~~~~~~~~^~~~~~~~~~
cookie-monster-bof.c:313:9: warning: implicit declaration of function ‘download_file’ [-Wimplicit-function-declaration]
  313 |         download_file(logins, buffer, dwFileSize);
      |         ^~~~~~~~~~~~~
cookie-monster-bof.c:323:34: warning: passing argument 1 of ‘KERNEL32$CreateFileA’ from incompatible pointer type [-Wincompatible-pointer-types]
  323 |     hFile = KERNEL32$CreateFileA(database, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
      |                                  ^~~~~~~~
      |                                  |
      |                                  CHAR * {aka char *}
cookie-monster-bof.c:24:57: note: expected ‘LPCWSTR’ {aka ‘const short unsigned int *’} but argument is of type ‘CHAR *’ {aka ‘char *’}
   24 | WINBASEAPI HANDLE  WINAPI KERNEL32$CreateFileA (LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
      |                                                 ~~~~~~~~^~~~~~~~~~
cookie-monster-bof.c: In function ‘GetBrowserFile’:
cookie-monster-bof.c:427:61: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  427 |                         if(!KERNEL32$DuplicateHandle(hProc, (HANDLE)shi->Handles[i].Handle, KERNEL32$GetCurrentProcess(), &hDuplicate, 0, TRUE, DUPLICATE_SAME_ACCESS)) {
      |                                                             ^
x86_64-w64-mingw32-strip --strip-unneeded cookie-monster-bof.o

**Comment by KingOfTheNOPs** [comment]
these all appear to be warning messages and expected behavior. Do you see cookie-monster-bof.o after running make?

**Comment by KingOfTheNOPs** [comment]
@7h3pr0xy are you still having any issues compiling the project?

**Comment by KingOfTheNOPs** [comment]
no issues compiling in my testing range, closing this issue. Feel free to reach out if you have any additional issues
