### ISSUE TITLE
Still working for Chrome and Edge cookies?

### ISSUE THREAD

**Issue by J1mX** [KingOfTheNOPs/cookie-monster#5]
Working fine for passwords from both Edge and Chrome but not cookies?
I can review further just wanted to check if this was a known issue with the standalone version none BOF?
PS: Great tool and scripts!

**Comment by KingOfTheNOPs** [comment]
Do you mind providing some more information? Output after you ran the BOF, are you on a Win 10 host (never tested it against Win11)? 

Have you tried running Handles (sysinternal tool) to see Chrome or MsEdge processes have a handle to a cookie DB? I ran into weird situations where my browser didn't have a handle to any cookie DB and after a reboot it was back to normal.

**Comment by KingOfTheNOPs** [comment]
thanks for bringing up the issue, hopefully this fixes it for ya.
